# Generated by Django 3.1.4 on 2021-04-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
