# Generated by Django 3.1.4 on 2021-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0005_booking_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='payment',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
