# Generated by Django 3.1.4 on 2021-04-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0006_auto_20210414_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
